/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColetaIdRouteImport } from './routes/coleta.$id'
import { Route as ColetaIdResumoRouteImport } from './routes/coleta.$id.resumo'

const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaIdRoute = ColetaIdRouteImport.update({
  id: '/coleta/$id',
  path: '/coleta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaIdResumoRoute = ColetaIdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => ColetaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/coleta/$id': typeof ColetaIdRouteWithChildren
  '/coleta/$id/resumo': typeof ColetaIdResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/coleta/$id': typeof ColetaIdRouteWithChildren
  '/coleta/$id/resumo': typeof ColetaIdResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/coleta/$id': typeof ColetaIdRouteWithChildren
  '/coleta/$id/resumo': typeof ColetaIdResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dados'
    | '/historico'
    | '/lista'
    | '/coleta/$id'
    | '/coleta/$id/resumo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dados'
    | '/historico'
    | '/lista'
    | '/coleta/$id'
    | '/coleta/$id/resumo'
  id:
    | '__root__'
    | '/'
    | '/dados'
    | '/historico'
    | '/lista'
    | '/coleta/$id'
    | '/coleta/$id/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DadosRoute: typeof DadosRoute
  HistoricoRoute: typeof HistoricoRoute
  ListaRoute: typeof ListaRoute
  ColetaIdRoute: typeof ColetaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta/$id': {
      id: '/coleta/$id'
      path: '/coleta/$id'
      fullPath: '/coleta/$id'
      preLoaderRoute: typeof ColetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta/$id/resumo': {
      id: '/coleta/$id/resumo'
      path: '/resumo'
      fullPath: '/coleta/$id/resumo'
      preLoaderRoute: typeof ColetaIdResumoRouteImport
      parentRoute: typeof ColetaIdRoute
    }
  }
}

interface ColetaIdRouteChildren {
  ColetaIdResumoRoute: typeof ColetaIdResumoRoute
}

const ColetaIdRouteChildren: ColetaIdRouteChildren = {
  ColetaIdResumoRoute: ColetaIdResumoRoute,
}

const ColetaIdRouteWithChildren = ColetaIdRoute._addFileChildren(
  ColetaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DadosRoute: DadosRoute,
  HistoricoRoute: HistoricoRoute,
  ListaRoute: ListaRoute,
  ColetaIdRoute: ColetaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
